# to renew the environement if changes needed
# conda env remove -n gencast  # (if needed)
# conda env create -f environment.yml
# conda activate gencast


# make it visible on the notebook kernel selection
# source ~/.bashrc   # if needed
# conda activate gencast   # or source activate gencast

# pip install ipykernel
# python -m ipykernel install --user --name=gencast --display-name "Python (gencast2)"


#pip install --upgrade "jax[cuda12]"

name: gencast
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - scipy
  - matplotlib
  - pandas
  - xarray=2023.12.0
  - netCDF4
  - dask
  - cartopy
  - ipywidgets
  - cdsapi
  - pip:
      # GraphCast from GitHub (master branch)
      - git+https://github.com/deepmind/graphcast.git@main
      # PyTorch with CUDA 12.4 support
      - torch==2.0.1
      - torchvision==0.15.2
      - torchaudio==2.0.2
      - -f https://download.pytorch.org/whl/cu124
      # Install JAX with CUDA 12 support
      - "jax[cuda12]"

        
  #     # JAX for CUDA 12, pinned to 0.4.23
  #     - "jax[cuda12]==0.4.23 -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html"
  #     # Haiku v0.0.9 from PyPI (the last release that still works with JAX 0.4.x)
  #     - dm-haiku==0.0.9
  

